version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - GLANCES_URL=${GLANCES_URL}
      - GLANCES_PASSWORD=${GLANCES_PASSWORD}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - dashboard-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dashboard-network

volumes:
  postgres_data:

networks:
  dashboard-network:
    driver: bridge